import { AnimationPreset } from '@slideforge/shared';

export const animationPresets: AnimationPreset[] = [
  {
    id: 'fade-in',
    name: 'Fade In',
    category: 'entrance',
    preview: 'fadeIn',
    config: {
      type: 'fade',
      trigger: 'auto',
      duration: 500,
      delay: 0,
      easing: 'ease-in-out',
      properties: { direction: 'in', opacity: 1 },
    },
  },
  {
    id: 'fade-out',
    name: 'Fade Out',
    category: 'exit',
    preview: 'fadeOut',
    config: {
      type: 'fade',
      trigger: 'auto',
      duration: 500,
      delay: 0,
      easing: 'ease-in-out',
      properties: { direction: 'out', opacity: 0 },
    },
  },
  {
    id: 'slide-in-left',
    name: 'Slide In from Left',
    category: 'entrance',
    preview: 'slideInLeft',
    config: {
      type: 'slide',
      trigger: 'auto',
      duration: 600,
      delay: 0,
      easing: 'power2.out',
      properties: { direction: 'left' },
    },
  },
  {
    id: 'slide-in-right',
    name: 'Slide In from Right',
    category: 'entrance',
    preview: 'slideInRight',
    config: {
      type: 'slide',
      trigger: 'auto',
      duration: 600,
      delay: 0,
      easing: 'power2.out',
      properties: { direction: 'right' },
    },
  },
  {
    id: 'slide-in-up',
    name: 'Slide In from Top',
    category: 'entrance',
    preview: 'slideInUp',
    config: {
      type: 'slide',
      trigger: 'auto',
      duration: 600,
      delay: 0,
      easing: 'power2.out',
      properties: { direction: 'up' },
    },
  },
  {
    id: 'slide-in-down',
    name: 'Slide In from Bottom',
    category: 'entrance',
    preview: 'slideInDown',
    config: {
      type: 'slide',
      trigger: 'auto',
      duration: 600,
      delay: 0,
      easing: 'power2.out',
      properties: { direction: 'down' },
    },
  },
  {
    id: 'slide-out-left',
    name: 'Slide Out to Left',
    category: 'exit',
    preview: 'slideOutLeft',
    config: {
      type: 'slide',
      trigger: 'auto',
      duration: 600,
      delay: 0,
      easing: 'power2.in',
      properties: { direction: 'left' },
    },
  },
  {
    id: 'slide-out-right',
    name: 'Slide Out to Right',
    category: 'exit',
    preview: 'slideOutRight',
    config: {
      type: 'slide',
      trigger: 'auto',
      duration: 600,
      delay: 0,
      easing: 'power2.in',
      properties: { direction: 'right' },
    },
  },
  {
    id: 'zoom-in',
    name: 'Zoom In',
    category: 'entrance',
    preview: 'zoomIn',
    config: {
      type: 'zoom',
      trigger: 'auto',
      duration: 500,
      delay: 0,
      easing: 'power2.out',
      properties: { direction: 'in', scale: 1 },
    },
  },
  {
    id: 'zoom-out',
    name: 'Zoom Out',
    category: 'exit',
    preview: 'zoomOut',
    config: {
      type: 'zoom',
      trigger: 'auto',
      duration: 500,
      delay: 0,
      easing: 'power2.in',
      properties: { direction: 'out', scale: 0 },
    },
  },
  {
    id: 'zoom-in-big',
    name: 'Zoom In (Large)',
    category: 'entrance',
    preview: 'zoomInBig',
    config: {
      type: 'zoom',
      trigger: 'auto',
      duration: 700,
      delay: 0,
      easing: 'elastic.out',
      properties: { direction: 'in', scale: 1.5 },
    },
  },
  {
    id: 'rotate-in',
    name: 'Rotate In',
    category: 'entrance',
    preview: 'rotateIn',
    config: {
      type: 'rotate',
      trigger: 'auto',
      duration: 700,
      delay: 0,
      easing: 'power3.out',
      properties: { rotationZ: 360 },
    },
  },
  {
    id: 'rotate-out',
    name: 'Rotate Out',
    category: 'exit',
    preview: 'rotateOut',
    config: {
      type: 'rotate',
      trigger: 'auto',
      duration: 700,
      delay: 0,
      easing: 'power3.in',
      properties: { rotationZ: -360 },
    },
  },
  {
    id: 'spin',
    name: 'Spin',
    category: 'emphasis',
    preview: 'spin',
    config: {
      type: 'rotate',
      trigger: 'auto',
      duration: 1000,
      delay: 0,
      easing: 'linear',
      properties: { rotationZ: 360 },
      repeat: 1,
    },
  },
  {
    id: 'bounce',
    name: 'Bounce',
    category: 'emphasis',
    preview: 'bounce',
    config: {
      type: 'custom',
      trigger: 'auto',
      duration: 1000,
      delay: 0,
      easing: 'bounce.out',
      properties: { y: 0 },
      keyframes: [
        { time: 0, properties: { y: 0 }, easing: 'bounce.out' },
        { time: 400, properties: { y: -30 }, easing: 'bounce.out' },
        { time: 1000, properties: { y: 0 }, easing: 'bounce.out' },
      ],
    },
  },
  {
    id: 'pulse',
    name: 'Pulse',
    category: 'emphasis',
    preview: 'pulse',
    config: {
      type: 'zoom',
      trigger: 'auto',
      duration: 600,
      delay: 0,
      easing: 'power1.inOut',
      properties: { scale: 1.1 },
      yoyo: true,
      repeat: 2,
    },
  },
  {
    id: 'shake',
    name: 'Shake',
    category: 'emphasis',
    preview: 'shake',
    config: {
      type: 'custom',
      trigger: 'auto',
      duration: 800,
      delay: 0,
      easing: 'power2.inOut',
      properties: {},
      keyframes: [
        { time: 0, properties: { x: 0 }, easing: 'power2.inOut' },
        { time: 100, properties: { x: -10 }, easing: 'power2.inOut' },
        { time: 200, properties: { x: 10 }, easing: 'power2.inOut' },
        { time: 300, properties: { x: -10 }, easing: 'power2.inOut' },
        { time: 400, properties: { x: 10 }, easing: 'power2.inOut' },
        { time: 500, properties: { x: -10 }, easing: 'power2.inOut' },
        { time: 600, properties: { x: 10 }, easing: 'power2.inOut' },
        { time: 700, properties: { x: -5 }, easing: 'power2.inOut' },
        { time: 800, properties: { x: 0 }, easing: 'power2.inOut' },
      ],
    },
  },
  {
    id: 'flip-in-x',
    name: 'Flip In (Horizontal)',
    category: '3d',
    preview: 'flipInX',
    config: {
      type: '3d',
      trigger: 'auto',
      duration: 800,
      delay: 0,
      easing: 'power2.out',
      properties: {
        rotationX: 0,
        perspective: 1000,
      },
      keyframes: [
        { time: 0, properties: { rotationX: -90, opacity: 0 }, easing: 'power2.out' },
        { time: 800, properties: { rotationX: 0, opacity: 1 }, easing: 'power2.out' },
      ],
    },
  },
  {
    id: 'flip-in-y',
    name: 'Flip In (Vertical)',
    category: '3d',
    preview: 'flipInY',
    config: {
      type: '3d',
      trigger: 'auto',
      duration: 800,
      delay: 0,
      easing: 'power2.out',
      properties: {
        rotationY: 0,
        perspective: 1000,
      },
      keyframes: [
        { time: 0, properties: { rotationY: -90, opacity: 0 }, easing: 'power2.out' },
        { time: 800, properties: { rotationY: 0, opacity: 1 }, easing: 'power2.out' },
      ],
    },
  },
  {
    id: 'flip-out-x',
    name: 'Flip Out (Horizontal)',
    category: '3d',
    preview: 'flipOutX',
    config: {
      type: '3d',
      trigger: 'auto',
      duration: 800,
      delay: 0,
      easing: 'power2.in',
      properties: {
        rotationX: 90,
        perspective: 1000,
      },
      keyframes: [
        { time: 0, properties: { rotationX: 0, opacity: 1 }, easing: 'power2.in' },
        { time: 800, properties: { rotationX: 90, opacity: 0 }, easing: 'power2.in' },
      ],
    },
  },
  {
    id: 'flip-out-y',
    name: 'Flip Out (Vertical)',
    category: '3d',
    preview: 'flipOutY',
    config: {
      type: '3d',
      trigger: 'auto',
      duration: 800,
      delay: 0,
      easing: 'power2.in',
      properties: {
        rotationY: 90,
        perspective: 1000,
      },
      keyframes: [
        { time: 0, properties: { rotationY: 0, opacity: 1 }, easing: 'power2.in' },
        { time: 800, properties: { rotationY: 90, opacity: 0 }, easing: 'power2.in' },
      ],
    },
  },
  {
    id: 'cube-rotate',
    name: '3D Cube Rotation',
    category: '3d',
    preview: 'cubeRotate',
    config: {
      type: '3d',
      trigger: 'auto',
      duration: 1200,
      delay: 0,
      easing: 'power1.inOut',
      properties: {
        rotationX: 360,
        rotationY: 360,
        perspective: 800,
      },
    },
  },
  {
    id: 'particle-explode',
    name: 'Particle Explosion',
    category: 'particle',
    preview: 'particleExplode',
    config: {
      type: 'particle',
      trigger: 'auto',
      duration: 2000,
      delay: 0,
      easing: 'power2.out',
      properties: {
        particleCount: 100,
        particleSize: 4,
        particleColor: '#ff6b6b',
        particleVelocity: { x: 0, y: -3 },
      },
    },
  },
  {
    id: 'particle-confetti',
    name: 'Confetti',
    category: 'particle',
    preview: 'particleConfetti',
    config: {
      type: 'particle',
      trigger: 'auto',
      duration: 3000,
      delay: 0,
      easing: 'power2.out',
      properties: {
        particleCount: 150,
        particleSize: 6,
        particleColor: '#4ecdc4',
        particleVelocity: { x: 0, y: -4 },
      },
    },
  },
  {
    id: 'particle-sparkle',
    name: 'Sparkle',
    category: 'particle',
    preview: 'particleSparkle',
    config: {
      type: 'particle',
      trigger: 'auto',
      duration: 1500,
      delay: 0,
      easing: 'power2.out',
      properties: {
        particleCount: 50,
        particleSize: 3,
        particleColor: '#ffd93d',
        particleVelocity: { x: 0, y: -2 },
      },
    },
  },
  {
    id: 'elastic-bounce',
    name: 'Elastic Bounce',
    category: 'entrance',
    preview: 'elasticBounce',
    config: {
      type: 'zoom',
      trigger: 'auto',
      duration: 1000,
      delay: 0,
      easing: 'elastic.out',
      properties: { direction: 'in', scale: 1 },
    },
  },
  {
    id: 'back-in-left',
    name: 'Back In from Left',
    category: 'entrance',
    preview: 'backInLeft',
    config: {
      type: 'custom',
      trigger: 'auto',
      duration: 800,
      delay: 0,
      easing: 'back.out',
      properties: { x: 0, opacity: 1 },
      keyframes: [
        { time: 0, properties: { x: -200, opacity: 0 }, easing: 'back.out' },
        { time: 800, properties: { x: 0, opacity: 1 }, easing: 'back.out' },
      ],
    },
  },
  {
    id: 'back-in-right',
    name: 'Back In from Right',
    category: 'entrance',
    preview: 'backInRight',
    config: {
      type: 'custom',
      trigger: 'auto',
      duration: 800,
      delay: 0,
      easing: 'back.out',
      properties: { x: 0, opacity: 1 },
      keyframes: [
        { time: 0, properties: { x: 200, opacity: 0 }, easing: 'back.out' },
        { time: 800, properties: { x: 0, opacity: 1 }, easing: 'back.out' },
      ],
    },
  },
  {
    id: 'swing',
    name: 'Swing',
    category: 'emphasis',
    preview: 'swing',
    config: {
      type: 'rotate',
      trigger: 'auto',
      duration: 1000,
      delay: 0,
      easing: 'power2.inOut',
      properties: { transformOrigin: 'top center' },
      keyframes: [
        { time: 0, properties: { rotationZ: 0 }, easing: 'power2.inOut' },
        { time: 200, properties: { rotationZ: 15 }, easing: 'power2.inOut' },
        { time: 400, properties: { rotationZ: -10 }, easing: 'power2.inOut' },
        { time: 600, properties: { rotationZ: 5 }, easing: 'power2.inOut' },
        { time: 800, properties: { rotationZ: -5 }, easing: 'power2.inOut' },
        { time: 1000, properties: { rotationZ: 0 }, easing: 'power2.inOut' },
      ],
    },
  },
  {
    id: 'wobble',
    name: 'Wobble',
    category: 'emphasis',
    preview: 'wobble',
    config: {
      type: 'custom',
      trigger: 'auto',
      duration: 1000,
      delay: 0,
      easing: 'power1.inOut',
      properties: {},
      keyframes: [
        { time: 0, properties: { x: 0, rotationZ: 0 }, easing: 'power1.inOut' },
        { time: 150, properties: { x: -25, rotationZ: -5 }, easing: 'power1.inOut' },
        { time: 300, properties: { x: 20, rotationZ: 3 }, easing: 'power1.inOut' },
        { time: 450, properties: { x: -15, rotationZ: -3 }, easing: 'power1.inOut' },
        { time: 600, properties: { x: 10, rotationZ: 2 }, easing: 'power1.inOut' },
        { time: 750, properties: { x: -5, rotationZ: -1 }, easing: 'power1.inOut' },
        { time: 1000, properties: { x: 0, rotationZ: 0 }, easing: 'power1.inOut' },
      ],
    },
  },
  {
    id: 'flash',
    name: 'Flash',
    category: 'emphasis',
    preview: 'flash',
    config: {
      type: 'fade',
      trigger: 'auto',
      duration: 800,
      delay: 0,
      easing: 'power1.inOut',
      properties: {},
      keyframes: [
        { time: 0, properties: { opacity: 1 }, easing: 'power1.inOut' },
        { time: 200, properties: { opacity: 0 }, easing: 'power1.inOut' },
        { time: 400, properties: { opacity: 1 }, easing: 'power1.inOut' },
        { time: 600, properties: { opacity: 0 }, easing: 'power1.inOut' },
        { time: 800, properties: { opacity: 1 }, easing: 'power1.inOut' },
      ],
    },
  },
];

export const getPresetsByCategory = (category: AnimationPreset['category']): AnimationPreset[] => {
  return animationPresets.filter(preset => preset.category === category);
};

export const getPresetById = (id: string): AnimationPreset | undefined => {
  return animationPresets.find(preset => preset.id === id);
};

export const getAllCategories = (): AnimationPreset['category'][] => {
  return ['entrance', 'exit', 'emphasis', 'motion', '3d', 'particle'];
};
